#!/usr/bin/env bash
# regen-model-abbrev.sh — Refresh the ModelAbbreviation.generated.json
# resource from the canonical providers.yaml SSOT.
#
# SSOT: ~/repos/llm-router/config/providers.yaml#display_abbreviations
# rules/81: data in registered SSOT, never duplicate. The JSON file is a
# build-time render of the YAML — both tmux (Python yaml.safe_load at runtime)
# and Cortex (Swift JSONDecoder at runtime, generated by this script) read
# from the same source.
#
# Usage:
#   ./scripts/regen-model-abbrev.sh           # write to default path
#   YAML=... ./scripts/regen-model-abbrev.sh  # override source
#
# Tuist 4.204.0 doesn't expose a public TargetScript factory, so this script
# is the manual counterpart of what would otherwise be an inline build phase.
# Run it after editing providers.yaml, before `tuist generate && tuist build`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
YAML="${YAML:-$HOME/repos/llm-router/config/providers.yaml}"
JSON="${JSON:-$REPO_ROOT/Sources/Domain/Provider/ModelAbbreviation.generated.json}"

if [ ! -f "$YAML" ]; then
    echo "error: YAML SSOT not found at $YAML" >&2
    echo "       set YAML=/path/to/providers.yaml to override." >&2
    exit 1
fi

python3 - "$YAML" "$JSON" <<'PYEOF'
import sys, yaml, json, os
yaml_path, json_path = sys.argv[1], sys.argv[2]
with open(yaml_path) as fh:
    data = yaml.safe_load(fh) or {}
flat = {}
for family, m in (data.get("display_abbreviations") or {}).items():
    if isinstance(m, dict):
        flat.update(m)
# Provenance without machine-specific absolute paths (public repo safe):
# relative to $HOME when inside it, else the basename.
home = os.path.expanduser("~") + os.sep
provenance = yaml_path[len(home):] if yaml_path.startswith(home) else os.path.basename(yaml_path)
with open(json_path, "w", encoding="utf-8") as fh:
    json.dump({
        "schema_version": 1,
        "source_yaml": provenance,
        "mappings": flat,
    }, fh, indent=2, ensure_ascii=False, sort_keys=True)
print(f"ModelAbbreviation regen: {len(flat)} mappings → {json_path}")
PYEOF
